[package]
name = "aura"
version = "4.0.0-r1"
authors = ["Colin Woodbury <colin@fosskers.ca>"]
edition = "2018"

[dependencies]
alpm = "1.0.0-rc2"
clap = "3.0.0-beta.2"
curl = "0.4"
fluent = "0.13.1"
indicatif = "0.15"
r2d2 = "0.8"
rayon = "1.5.0"
unic-langid = { version = "0.9", features = ["macros"] }

[profile.release]
lto = true