[package]
name = "aura"
version = "4.0.0-r1"
authors = ["Colin Woodbury <colin@fosskers.ca>"]
edition = "2018"

[dependencies]
alpm = "1.0.0-rc2"
clap = "3.0.0-beta.2"
curl = "0.4"

[profile.release]
lto = true